### PR TITLE
changed nav bar shadows

### PR DESCRIPTION
**Pull request by Saishreekouda**
Hey @kaal-coder, I was trying different shadows and thought that it looker better off without the shadows. So I made those changes and the Subscribe us button in the nav bar was looking different from the one below so made them look similar for a consistent look. Apart from that, I made a few alignment changes.

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Saishreekouda please share a preview of the changes made.

**Comment by Saishreekouda** [comment]
image

Here is the preview @kaal-coder

**Comment by kaal-coder** [comment]
I was expecting a better design and hence I gave you medium level so that you have enough time to change. 
Do you want to add more styling in this or else I have to merge this under easy level.

**Comment by Saishreekouda** [comment]
@kaal-coder i will make more changes to this

**Comment by kaal-coder** [comment]
Okay

**Comment by Saishreekouda** [comment]
Screenshot 2023-02-28 at 12 23 08 AM
@kaal-coder changed the padding to decrease the white spaces on the screen and also changed the bottom line to the centre of the page with lesser opacity

**Pull request closed without merging**
