### PR TITLE
Destination page for logo

### PR DESCRIPTION
**Pull request by vk20july**
@kaal-coder Sir kindly review my code
#90

### CODE REVIEW

**Comment by kaal-coder** [comment]
https://github.com/MightyITExplorer/Website/issues/90#issuecomment-1455029775
Fix the navbar position at top even while scrolling down. 
Share a preview of the same with a video

**Comment by vk20july** [comment]
Ok sir i will do
Sir is it possible to change the difficulty to medium

**Comment by kaal-coder** [comment]
I have already mentioned in the issues that the level will be easy.

**Comment by vk20july** [comment]
Ok sir

**Comment by vk20july** [comment]
@kaal-coder sir made the required changes kindly review

**Comment by kaal-coder** [comment]
@vk20july please update the branch and provide a preview in the form of image/video for the changes you have made.

**Comment by vk20july** [comment]
Uploading Mighty IT Explorer - Opera 2023-03-07 13-58-03 (1).mp4…

**Comment by vk20july** [comment]
https://user-images.githubusercontent.com/71543332/223367809-a9df78f0-80a1-4fc8-a273-75bc2b0c7eaf.mp4

**Comment by vk20july** [comment]
@kaal-coder made the required changes please review

**Pull request closed without merging**
