### PR TITLE
updated css files

### PR DESCRIPTION
**Pull request by Code1705**
please could you merge my PR?

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Code1705 please share a preview of changes.

**Comment by Code1705** [comment]
Screenshot (46)

**Comment by Code1705** [comment]
Screenshot (48)

**Comment by kaal-coder** [comment]
changes that happened in the website after you modified the code.

**Comment by Code1705** [comment]
Screenshot (57)

**Comment by Code1705** [comment]
above given is the screenshot of the changes, now please could you merge my pr?

**Comment by Code1705** [comment]
please could you merge my pr?

**Comment by Code1705** [comment]
I have committed changes.. please could you merge my PR?

**Comment by Code1705** [comment]
#28 issue solved , merge my pr.

**Pull request merged**
