### PR TITLE
Design testimonial card

### PR DESCRIPTION
**Pull request by Awesomeasma**

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Awesomeasma please share a preview in the form of a screenshot/video of the changes made.

**Comment by Awesomeasma** [comment]
testimonial-card

**Comment by Awesomeasma** [comment]
> @Awesomeasma please share a preview in the form of a screenshot/video of the changes made.

@kaal-coder I apologise for the late response.

**Comment by Awesomeasma** [comment]
Please review it and let me know if u want further modifications.

**Comment by Awesomeasma** [comment]
@kaal-coder 
I have made the changes and created a new pull request - #104 
Please review it and let me know if u need further modifications..

**Comment by Awesomeasma** [comment]
testimonial

**Comment by Awesomeasma** [comment]
The swipe buttons are working as well..

**Pull request closed without merging**
