### PR TITLE
added report-bug-page

### PR DESCRIPTION
**Pull request by Awesomeasma**

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Awesomeasma please share a preview in the form of a screenshot/video of the changes made.

**Comment by kaal-coder** [comment]
@Awesomeasma any updates

**Comment by Awesomeasma** [comment]
report-bug-page

**Comment by Awesomeasma** [comment]
> @Awesomeasma please share a preview in the form of a screenshot/video of the changes made.

@kaal-coder I am sorry for the late response, I was in journey and hence couldn't reply on time.

**Comment by kaal-coder** [comment]
after clicking on the submit report button, where the response will be submitted ?

**Comment by Awesomeasma** [comment]
> after clicking on the submit report button, where the response will be submitted ?

I haven't completed the functionality of the 'submit' button yet, as I thought the task was to design it.

**Comment by Awesomeasma** [comment]
> > after clicking on the submit report button, where the response will be submitted ?
> 
> I haven't completed the functionality of the 'submit' button yet, as I thought the task was to design it.

If you want me to add further changes, I will do that right away..

**Comment by Awesomeasma** [comment]
> > > after clicking on the submit report button, where the response will be submitted ?
> > 
> > 
> > I haven't completed the functionality of the 'submit' button yet, as I thought the task was to design it.
> 
> If you want me to add further changes, I will do that right away..

Please let me know if u want me to implement functionality .

**Comment by kaal-coder** [comment]
@Awesomeasma add the functionality. Let me know how are you going to do the same.
Note - I will be increasing the level for that.

**Comment by Awesomeasma** [comment]
> @Awesomeasma add the functionality. Let me know how are you going to do the same. Note - I will be increasing the level for that.

I want to use 'Mockbin' to simulate the behavior of a server-side endpoint.     
If the server responds with a status code of 200 OK, the form is reset using the form.reset() method, and a success message is displayed to the user by removing the 'hidden' class from the element with the ID 'success-message'. If the server responds with an error status code, the error message is displayed to the user by removing the 'hidden' class from the element with the ID 'error-message'.

**Comment by Awesomeasma** [comment]
Shall I work on that ??

**Comment by Awesomeasma** [comment]
I have updated the report-bug-js file accordingly. Please review it and tell me if u need any further modifications.

**Pull request merged**
