### PR TITLE
Add Scroll To Top Button

### PR DESCRIPTION
**Pull request by SattyamSamania**
I have added Scroll to Top Button using HTML, CSS and Javascript.
HTML code - index.html
CSS code - index.css
Javascript code - theme.js
Feel free to give any suggestions if required. Thank you!

### CODE REVIEW

**Comment by kaal-coder** [comment]
@SattyamSamania please share a preview of the changes made.

**Comment by SattyamSamania** [comment]
> @SattyamSamania please share a preview of the changes made.

Sure @kaal-coder I am sending the screen recording of the changes made.

**Comment by SattyamSamania** [comment]
> @SattyamSamania please share a preview of the changes made.


https://user-images.githubusercontent.com/67833888/221388432-ddcecf76-6684-49c0-a87e-3e0e1a5c70e4.mp4

**Comment by kaal-coder** [comment]
The screen vibration. Is there any error in your pc or there's error in website code ?

**Comment by SattyamSamania** [comment]
> The screen vibration. Is there any error in your pc or there's error in website code ?

The error is in my PC, Because it lags when i make a screen recording. There is no error in the website's code.

**Pull request merged**
