### PR TITLE
Contact us form Validations added

### PR DESCRIPTION
**Pull request by harshit21-02**

### CODE REVIEW

**Comment by kaal-coder** [comment]
@harshit21-02 will the response submitted by user reach out in email ?

**Comment by harshit21-02** [comment]
@kaal-coder on which mail id do we need to send form data

**Comment by kaal-coder** [comment]
[mightyitexplorer@gmail.com](mailto:mightyitexplorer@gmail.com)

**Comment by harshit21-02** [comment]
I was trying formspree for this but it asks to verify the email

**Comment by kaal-coder** [comment]
okay. I'll do that.

**Pull request merged**
