### PR TITLE
Added custom css scrollbar

### LINKED ISSUE #12: Add a custom css scroll bar
Would like to add a custom css scrollbar which would improve the UI of the website.
@kaal-coder , please assign me this issue

### PR DESCRIPTION
**Pull request by Arbtrage**
closes #12 

ezgif com-video-to-gif

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Arbtrage in the home page, it isn't showing. Please have a look and do the needful.

**Comment by Arbtrage** [comment]
@kaal-coder , I checked the hosted website , it is showing there .
image

**Comment by kaal-coder** [comment]
@Arbtrage https://mightyitexplorer.netlify.app/ is it showing here ?

**Comment by Arbtrage** [comment]
@kaal-coder , yes it is..

**Comment by Arbtrage** [comment]
@kaal-coder , please add the JWOC label cuz in the leaderboard this PR is not showing.

**Pull request merged**
