### PR TITLE
Changed the color of the Subscribe us button, added more styling to the navbar .

### PR DESCRIPTION
**Pull request by Arbtrage**
closes issue #29 

@kaal-coder , please review these changes .

### CODE REVIEW

**Comment by kaal-coder** [comment]
@Arbtrage [fixed](https://github.com/MightyITExplorer/Website/issues/58#issuecomment-1444081477) this  ?

**Comment by Arbtrage** [comment]
No, it is new bug and someone else is already working on it ig .

**Comment by Arbtrage** [comment]
Changes I have made : 
- [x] Changed the color of the subscribe us button in the navbar .
- [x] Changed the font of the navbar text .
- [x] Added hover effect to navbar link .

**Comment by Arbtrage** [comment]
@kaal-coder , please add JWOC tag .

**Comment by Arbtrage** [comment]
In the issue it was mentioned Medium level difficulty , how come it is easy here ?

**Comment by kaal-coder** [comment]
Depending on the change you have done in navbar, accordingly the level is decided. In issues we don't see the end result

**Comment by Arbtrage** [comment]
Wow...

**Pull request merged**
